.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Fill" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Fill \- \fBFill\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFill\fP (\fBDrawer\fP drawer, bool enable)"
.br
.RI "\fBFill\fP enables or disables the fill insider drawer "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Sets the fill status "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes what the command will do "
.in -1c
.SH "Detailed Description"
.PP 
\fBFill\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Fill\&.Fill (\fBDrawer\fP drawer, bool enable)"

.PP
\fBFill\fP enables or disables the fill insider drawer 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIenable\fP Enable fill?
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Fill\&.ExecuteVerb ()"

.PP
Sets the fill status 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Fill\&.GetDescription ()"

.PP
Describes what the command will do 
.PP
\fBReturns\fP
.RS 4
Description of what the \fBIVerb\fP will do
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
