.TH "Advanced_Software_Engineering.Verbs.Flow.ForChunk" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Flow.ForChunk \- A \fBForChunk\fP is similar to a \fBWhileChunk\fP\&. It executes a specific number of times\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.Verbs\&.Flow\&.VerbChunk\fP, \fBAdvanced_Software_Engineering\&.Verbs\&.Flow\&.IVerbChunk\fP, and \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForChunk\fP (\fBValueStorage\fP valueStorage, \fBIValue\fP conditional)"
.br
.RI "A For Loop object "
.ti -1c
.RI "\fBForChunk\fP (\fBValueStorage\fP valueStorage, \fBIValue\fP conditional, \fBIVerb\fP oneLineVerb)"
.br
.RI "A For Loop object "
.ti -1c
.RI "new void \fBExecuteVerb\fP ()"
.br
.RI "Executes the chunk the number of specified times "
.in -1c
.SH "Detailed Description"
.PP 
A \fBForChunk\fP is similar to a \fBWhileChunk\fP\&. It executes a specific number of times\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.Flow\&.ForChunk\&.ForChunk (\fBValueStorage\fP valueStorage, \fBIValue\fP conditional)"

.PP
A For Loop object 
.PP
\fBParameters\fP
.RS 4
\fIvalueStorage\fP The ValueStorage for increasing and decreasing the stack
.br
\fIconditional\fP Preferably Value\&.ValueTypes\&.IntValue, the number of times the loop should execute\&.
.RE
.PP

.SS "Advanced_Software_Engineering\&.Verbs\&.Flow\&.ForChunk\&.ForChunk (\fBValueStorage\fP valueStorage, \fBIValue\fP conditional, \fBIVerb\fP oneLineVerb)"

.PP
A For Loop object 
.PP
\fBParameters\fP
.RS 4
\fIvalueStorage\fP The ValueStorage for increasing and decreasing the stack
.br
\fIconditional\fP Preferably Value\&.ValueTypes\&.IntValue, the number of times the loop should execute\&.
.br
\fIoneLineVerb\fP A verb to execute in a single line
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "new void Advanced_Software_Engineering\&.Verbs\&.Flow\&.ForChunk\&.ExecuteVerb ()"

.PP
Executes the chunk the number of specified times 
.PP
Implements \fBAdvanced_Software_Engineering\&.Verbs\&.Flow\&.IVerbChunk\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
