.TH "Advanced_Software_Engineering_Tests" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering_Tests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandTester\fP"
.br
.RI "The \fBCommandTester\fP class tests the commands possible, mostly by getting a IVerb and checking it's description\&.\&. "
.ti -1c
.RI "class \fBHelperFunctionsTester\fP"
.br
.RI "This class tests HelperFunctions methods\&. It uses a combination of manual and random tests\&. "
.ti -1c
.RI "class \fBValueHelperTester\fP"
.br
.RI "This class tests ValueHelper methods\&. It uses a combination of manual and random tests\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
