.TH "Advanced_Software_Engineering.Verbs.Flow" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Flow
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeclareMethod\fP"
.br
.RI "Declares a method\&. See DrawingVerbs\&.Actions\&.NoOp because these classes behave similarly "
.ti -1c
.RI "class \fBForChunk\fP"
.br
.RI "A \fBForChunk\fP is similar to a \fBWhileChunk\fP\&. It executes a specific number of times\&. "
.ti -1c
.RI "class \fBIfChunk\fP"
.br
.RI "A simple If Object "
.ti -1c
.RI "interface \fBIVerbChunk\fP"
.br
.RI "A Collection of chunks to be executed\&. They extend \fBIVerb\fP because they should be interchangable\&. "
.ti -1c
.RI "class \fBMethodChunk\fP"
.br
.RI "The method chunk class "
.ti -1c
.RI "class \fBVerbChunk\fP"
.br
.RI "A simple \fBVerbChunk\fP\&. Used for storing and executing a bunch of verbs "
.ti -1c
.RI "class \fBWhileChunk\fP"
.br
.RI "A Chunk that loops over its code "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
