.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.PenColor" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.PenColor \- The \fBPenColor\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPenColor\fP (\fBDrawer\fP drawer, \fBIValue\fP color)"
.br
.RI "Creates a \fBPenColor\fP instance "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Sets the pen color "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes the pen color "
.in -1c
.SH "Detailed Description"
.PP 
The \fBPenColor\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.PenColor\&.PenColor (\fBDrawer\fP drawer, \fBIValue\fP color)"

.PP
Creates a \fBPenColor\fP instance 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIcolor\fP Pen color
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.PenColor\&.ExecuteVerb ()"

.PP
Sets the pen color 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.PenColor\&.GetDescription ()"

.PP
Describes the pen color 
.PP
\fBReturns\fP
.RS 4
The description pen color
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
