.TH "Advanced_Software_Engineering_Tests.HelperFunctionsTester" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering_Tests.HelperFunctionsTester \- This class tests HelperFunctions methods\&. It uses a combination of manual and random tests\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStrip_Random1\fP ()"
.br
.RI "Random strip spaces test "
.ti -1c
.RI "void \fBStrip_Manual1\fP ()"
.br
.RI "Manual HelperFunctions\&.Strip(string) test "
.ti -1c
.RI "void \fBStrip_Manual2\fP ()"
.br
.RI "Manual HelperFunctions\&.Strip(string) test "
.ti -1c
.RI "void \fBStripStringArray_Manual1\fP ()"
.br
.RI "Manual HelperFunctions\&.StripStringArray(string[]) test\&. "
.ti -1c
.RI "void \fBStripStringArray_Manual2\fP ()"
.br
.RI "Manual HelperFunctions\&.StripStringArray(string[]) test\&. "
.ti -1c
.RI "void \fBCommandAndParameterParser_Manual1\fP ()"
.br
.RI "Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. "
.ti -1c
.RI "void \fBCommandAndParameterParser_Manual2\fP ()"
.br
.RI "Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. "
.ti -1c
.RI "void \fBCommandAndParameterParser_Manual3\fP ()"
.br
.RI "Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. "
.ti -1c
.RI "void \fBCommandAndParameterParser_Manual4\fP ()"
.br
.RI "Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. "
.ti -1c
.RI "void \fBCommandAndParameterParser_Random1\fP ()"
.br
.RI "Random HelperFunctions\&.CommandAndParameterParser(string) test\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class tests HelperFunctions methods\&. It uses a combination of manual and random tests\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.CommandAndParameterParser_Manual1 ()"

.PP
Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.CommandAndParameterParser_Manual2 ()"

.PP
Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.CommandAndParameterParser_Manual3 ()"

.PP
Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.CommandAndParameterParser_Manual4 ()"

.PP
Manual HelperFunctions\&.CommandAndParameterParser(string) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.CommandAndParameterParser_Random1 ()"

.PP
Random HelperFunctions\&.CommandAndParameterParser(string) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.Strip_Manual1 ()"

.PP
Manual HelperFunctions\&.Strip(string) test 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.Strip_Manual2 ()"

.PP
Manual HelperFunctions\&.Strip(string) test 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.Strip_Random1 ()"

.PP
Random strip spaces test 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.StripStringArray_Manual1 ()"

.PP
Manual HelperFunctions\&.StripStringArray(string[]) test\&. 
.SS "void Advanced_Software_Engineering_Tests\&.HelperFunctionsTester\&.StripStringArray_Manual2 ()"

.PP
Manual HelperFunctions\&.StripStringArray(string[]) test\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
