.TH "Advanced_Software_Engineering.TextEditor" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.TextEditor \- Auto generated code  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditor\fP ()"
.br
.RI "The text editor is the main window that the user will be using for writing code\&. "
.ti -1c
.RI "\fBTextEditor\fP (OpenFileDialog openFile)"
.br
.RI "The text editor is the main window that the user will be using for writing code\&. "
.ti -1c
.RI "void \fBCheckCode\fP ()"
.br
.RI "This function checks if the code written is OK "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Auto generated code 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.TextEditor\&.TextEditor ()"

.PP
The text editor is the main window that the user will be using for writing code\&. 
.SS "Advanced_Software_Engineering\&.TextEditor\&.TextEditor (OpenFileDialog openFile)"

.PP
The text editor is the main window that the user will be using for writing code\&. 
.PP
\fBParameters\fP
.RS 4
\fIopenFile\fP File dialog which points to the file to open
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.TextEditor\&.CheckCode ()"

.PP
This function checks if the code written is OK 
.SS "override void Advanced_Software_Engineering\&.TextEditor\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
