.TH "Advanced_Software_Engineering.CommandHelp" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.CommandHelp \- This class is resposible for the command help window\&. The command help window shows help for the commands\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandHelp\fP ()"
.br
.RI "Initilize \fBCommandHelp\fP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class is resposible for the command help window\&. The command help window shows help for the commands\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.CommandHelp\&.CommandHelp ()"

.PP
Initilize \fBCommandHelp\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void Advanced_Software_Engineering\&.CommandHelp\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
