.TH "Advanced_Software_Engineering.Menu" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Menu \- Auto generated code\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenu\fP ()"
.br
.RI "This creates the main menu window you see when launching the program\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Auto generated code\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Menu\&.Menu ()"

.PP
This creates the main menu window you see when launching the program\&. This program window is only meant to show at launch and when all of the other windows are closed\&. It launches all windows independently of each other, so a theoretically unlimited number of windows can exist\&. 
.SH "Member Function Documentation"
.PP 
.SS "override void Advanced_Software_Engineering\&.Menu\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
