.TH "Advanced_Software_Engineering.CommandAndParameterParserResult" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.CommandAndParameterParserResult \- This class is a direct replacement to the dictionaries that were returned by \fBHelperFunctions\&.CommandAndParameterParser(string)\fP\&. This class provides better intraface to the output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandAndParameterParserResult\fP (string command, string[] parameters)"
.br
.RI "Generates a new Result "
.ti -1c
.RI "string \fBGetCommand\fP ()"
.br
.RI "Gets the command from the result "
.ti -1c
.RI "string[] \fBGetParameters\fP ()"
.br
.RI "Gets the command parameters "
.in -1c
.SH "Detailed Description"
.PP 
This class is a direct replacement to the dictionaries that were returned by \fBHelperFunctions\&.CommandAndParameterParser(string)\fP\&. This class provides better intraface to the output\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.CommandAndParameterParserResult\&.CommandAndParameterParserResult (string command, string[] parameters)"

.PP
Generates a new Result 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP The command
.br
\fIparameters\fP The parameters
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "string Advanced_Software_Engineering\&.CommandAndParameterParserResult\&.GetCommand ()"

.PP
Gets the command from the result 
.PP
\fBReturns\fP
.RS 4
the command
.RE
.PP

.SS "string [] Advanced_Software_Engineering\&.CommandAndParameterParserResult\&.GetParameters ()"

.PP
Gets the command parameters 
.PP
\fBReturns\fP
.RS 4
command parameters
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
