.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.ResetPen" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.ResetPen \- Setsets the pen to the initial position\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResetPen\fP (\fBDrawer\fP drawer)"
.br
.RI "Creates the \fBResetPen\fP \fBIVerb\fP "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Moves the pen to 0, 0 "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Gets the description of the command\&. "
.in -1c
.SH "Detailed Description"
.PP 
Setsets the pen to the initial position\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.ResetPen\&.ResetPen (\fBDrawer\fP drawer)"

.PP
Creates the \fBResetPen\fP \fBIVerb\fP 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.ResetPen\&.ExecuteVerb ()"

.PP
Moves the pen to 0, 0 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.ResetPen\&.GetDescription ()"

.PP
Gets the description of the command\&. 
.PP
\fBReturns\fP
.RS 4
The description of the command
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
