.TH "Advanced_Software_Engineering" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbout_Window\fP"
.br
.RI "Auto generated code "
.ti -1c
.RI "class \fBCommandAndParameterParserResult\fP"
.br
.RI "This class is a direct replacement to the dictionaries that were returned by \fBHelperFunctions\&.CommandAndParameterParser(string)\fP\&. This class provides better intraface to the output\&. "
.ti -1c
.RI "class \fBCommander\fP"
.br
.RI "The commander class takes care of commands\&. It also takes control of the drawer\&. "
.ti -1c
.RI "class \fBCommandHelp\fP"
.br
.RI "This class is resposible for the command help window\&. The command help window shows help for the commands\&. "
.ti -1c
.RI "class \fBConverters\fP"
.br
.ti -1c
.RI "class \fBDetailsWindow\fP"
.br
.RI "This form is reponsible for showing details\&. It is essentially a textbox in a form\&. "
.ti -1c
.RI "class \fBDraw_Preview\fP"
.br
.RI "Auto Generated Code "
.ti -1c
.RI "class \fBDrawer\fP"
.br
.RI "The drawer is responsible for drawing on the graphics object\&. "
.ti -1c
.RI "class \fBErrorWindow\fP"
.br
.RI "The error window that can show errors, warnings and messages\&. "
.ti -1c
.RI "class \fBHelperFunctions\fP"
.br
.RI "This class simply provides settings and some functions that are used across many components\&. "
.ti -1c
.RI "interface \fBIVerb\fP"
.br
.RI "\fBIVerb\fP is an interface for executing and getting the descriptions of \fBVerbs\fP\&. Some \fBVerbs\fP draw lines, some verbs will assign "
.ti -1c
.RI "class \fBMenu\fP"
.br
.RI "Auto generated code\&. "
.ti -1c
.RI "class \fBMenuManager\fP"
.br
.RI "\fBMenu\fP manager manages if the menu is shown to the user\&. It is a static class because every Form should be able to see it\&. See \fBMenu\fP\&. "
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBTextEditor\fP"
.br
.RI "Auto generated code "
.ti -1c
.RI "class \fBVerbFactory\fP"
.br
.RI "This class is responsible for creating \fBVerbs\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
