.TH "Advanced_Software_Engineering.DetailsWindow" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.DetailsWindow \- This form is reponsible for showing details\&. It is essentially a textbox in a form\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetailsWindow\fP (string details)"
.br
.RI "A details window dedicated to showing details\&. "
.ti -1c
.RI "\fBDetailsWindow\fP (string details, string title)"
.br
.RI "A details window that shows details in the textbox and title as the window title\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
This form is reponsible for showing details\&. It is essentially a textbox in a form\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.DetailsWindow\&.DetailsWindow (string details)"

.PP
A details window dedicated to showing details\&. 
.PP
\fBParameters\fP
.RS 4
\fIdetails\fP The textbox text
.RE
.PP

.SS "Advanced_Software_Engineering\&.DetailsWindow\&.DetailsWindow (string details, string title)"

.PP
A details window that shows details in the textbox and title as the window title\&. 
.PP
\fBParameters\fP
.RS 4
\fIdetails\fP the details to be shown in the textbox
.br
\fItitle\fP the title of the window
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void Advanced_Software_Engineering\&.DetailsWindow\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
