.TH "Advanced_Software_Engineering.Verbs.Value.ValueTypes" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value.ValueTypes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoolValue\fP"
.br
.ti -1c
.RI "class \fBComparisonValue\fP"
.br
.ti -1c
.RI "class \fBDoubleValue\fP"
.br
.ti -1c
.RI "class \fBIntValue\fP"
.br
.ti -1c
.RI "class \fBVariableValue\fP"
.br
.RI "Variable value is responsible for setting up values for \fBUpdateVariable\fP to then update "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
