.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.MoveTo" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.MoveTo \- \fBMoveTo\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveTo\fP (\fBDrawer\fP drawer, \fBPointValue\fP point)"
.br
.RI "Creates a \fBMoveTo\fP instance "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Moves the pen to the position "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes where the pen will move\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBMoveTo\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.MoveTo\&.MoveTo (\fBDrawer\fP drawer, \fBPointValue\fP point)"

.PP
Creates a \fBMoveTo\fP instance 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIpoint\fP Position to move to
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.MoveTo\&.ExecuteVerb ()"

.PP
Moves the pen to the position 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.MoveTo\&.GetDescription ()"

.PP
Describes where the pen will move\&. 
.PP
\fBReturns\fP
.RS 4
Description where the pen will move to
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
