.TH "Advanced_Software_Engineering_Tests.CommandTester" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering_Tests.CommandTester \- The \fBCommandTester\fP class tests the commands possible, mostly by getting a IVerb and checking it's description\&.\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVerbFactoryTester_Automatic1\fP ()"
.br
.RI "Automatically tests: "
.ti -1c
.RI "void \fBMoveToTester_Manual1\fP ()"
.br
.RI "tests the 'move' command\&. See MoveTo\&. "
.ti -1c
.RI "void \fBMoveToTester_Manual2\fP ()"
.br
.RI "tests the 'moveto' command\&. See MoveTo\&. "
.ti -1c
.RI "void \fBDrawToTester_Manual1\fP ()"
.br
.RI "tests the 'drawto' command\&. See DrawTo\&. "
.ti -1c
.RI "void \fBDrawToTester_Manual2\fP ()"
.br
.RI "tests the 'line' command\&. See DrawTo\&. "
.ti -1c
.RI "void \fBDrawToTester_Manual3\fP ()"
.br
.RI "tests the 'lineto' command\&. See DrawTo\&. "
.ti -1c
.RI "void \fBRegularPolygonTester_Manual1\fP ()"
.br
.RI "tests the 'regularpolygon' command\&. See RegularPolygon\&. "
.ti -1c
.RI "void \fBRegularPolygonTester_Manual2\fP ()"
.br
.RI "tests the 'rp' command\&. See RegularPolygon\&. "
.ti -1c
.RI "void \fBRegularPolygonTester_Manual3\fP ()"
.br
.RI "tests the 'regularpolygon' command\&. See RegularPolygon\&. "
.ti -1c
.RI "void \fBRegularPolygonTester_Manual4\fP ()"
.br
.RI "tests the 'rp' command\&. See RegularPolygon\&. "
.ti -1c
.RI "void \fBSquareTester_Manual1\fP ()"
.br
.RI "tests the 'square' command\&. See Square\&. "
.ti -1c
.RI "void \fBSquareTester_Manual2\fP ()"
.br
.RI "tests the 'square' command\&. See Square\&. "
.ti -1c
.RI "void \fBCircleTester_Manual1\fP ()"
.br
.RI "Tests the 'circle' command\&. See Circle\&. "
.ti -1c
.RI "void \fBTriangleTester_Manual1\fP ()"
.br
.RI "tests the 'triangle' command\&. See Triangle\&. "
.ti -1c
.RI "void \fBTriangleTester_Manual2\fP ()"
.br
.RI "tests the 'triangle' command\&. See Triangle\&. "
.ti -1c
.RI "void \fBDotTester_Manual1\fP ()"
.br
.RI "test the 'dot' command\&. See Dot\&. "
.ti -1c
.RI "void \fBClearTester_Manual1\fP ()"
.br
.RI "tests the 'clear' command\&. See Circle\&. "
.ti -1c
.RI "void \fBResetPenTester_Manual1\fP ()"
.br
.RI "Tests the 'reset' command\&. See ResetPen "
.ti -1c
.RI "void \fBResetPenTester_Manual2\fP ()"
.br
.RI "Tests the 'resetpen' command\&. See ResetPen\&. "
.ti -1c
.RI "void \fBPenTester_Manual1\fP ()"
.br
.RI "Tests the command 'pen'\&. See PenColor "
.ti -1c
.RI "void \fBFillTester_Manual1\fP ()"
.br
.RI "Tests the command 'fill'\&. See FillColor\&. "
.ti -1c
.RI "void \fBIfTester_Manual1\fP ()"
.br
.RI "Tests the 'if' command\&. It hasn't been implemented yet\&. "
.ti -1c
.RI "void \fBMethodTester_Manual1\fP ()"
.br
.RI "Tests the 'def' command\&. It hasn't been implemented yet\&. "
.ti -1c
.RI "void \fBValueTester_Manual1\fP ()"
.br
.RI "Tests the 'int' declaration and assignment\&. It hasn't been implemented yet\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBCommandTester\fP class tests the commands possible, mostly by getting a IVerb and checking it's description\&.\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.CircleTester_Manual1 ()"

.PP
Tests the 'circle' command\&. See Circle\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.ClearTester_Manual1 ()"

.PP
tests the 'clear' command\&. See Circle\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.DotTester_Manual1 ()"

.PP
test the 'dot' command\&. See Dot\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.DrawToTester_Manual1 ()"

.PP
tests the 'drawto' command\&. See DrawTo\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.DrawToTester_Manual2 ()"

.PP
tests the 'line' command\&. See DrawTo\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.DrawToTester_Manual3 ()"

.PP
tests the 'lineto' command\&. See DrawTo\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.FillTester_Manual1 ()"

.PP
Tests the command 'fill'\&. See FillColor\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.IfTester_Manual1 ()"

.PP
Tests the 'if' command\&. It hasn't been implemented yet\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.MethodTester_Manual1 ()"

.PP
Tests the 'def' command\&. It hasn't been implemented yet\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.MoveToTester_Manual1 ()"

.PP
tests the 'move' command\&. See MoveTo\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.MoveToTester_Manual2 ()"

.PP
tests the 'moveto' command\&. See MoveTo\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.PenTester_Manual1 ()"

.PP
Tests the command 'pen'\&. See PenColor 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.RegularPolygonTester_Manual1 ()"

.PP
tests the 'regularpolygon' command\&. See RegularPolygon\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.RegularPolygonTester_Manual2 ()"

.PP
tests the 'rp' command\&. See RegularPolygon\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.RegularPolygonTester_Manual3 ()"

.PP
tests the 'regularpolygon' command\&. See RegularPolygon\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.RegularPolygonTester_Manual4 ()"

.PP
tests the 'rp' command\&. See RegularPolygon\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.ResetPenTester_Manual1 ()"

.PP
Tests the 'reset' command\&. See ResetPen 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.ResetPenTester_Manual2 ()"

.PP
Tests the 'resetpen' command\&. See ResetPen\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.SquareTester_Manual1 ()"

.PP
tests the 'square' command\&. See Square\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.SquareTester_Manual2 ()"

.PP
tests the 'square' command\&. See Square\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.TriangleTester_Manual1 ()"

.PP
tests the 'triangle' command\&. See Triangle\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.TriangleTester_Manual2 ()"

.PP
tests the 'triangle' command\&. See Triangle\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.ValueTester_Manual1 ()"

.PP
Tests the 'int' declaration and assignment\&. It hasn't been implemented yet\&. 
.SS "void Advanced_Software_Engineering_Tests\&.CommandTester\&.VerbFactoryTester_Automatic1 ()"

.PP
Automatically tests: 
.IP "\(bu" 2
moveto
.IP "\(bu" 2
drawto
.IP "\(bu" 2
line
.IP "\(bu" 2
rp Current todo list:
.IP "\(bu" 2
square
.IP "\(bu" 2
rectangle
.IP "\(bu" 2
circle
.IP "\(bu" 2
triangle
.IP "\(bu" 2
dot
.IP "\(bu" 2
clear
.IP "\(bu" 2
pen
.IP "\(bu" 2
fill
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
