.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Rectangle" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Rectangle \- \fBRectangle\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangle\fP (\fBDrawer\fP drawer, \fBIValue\fP width, \fBIValue\fP height)"
.br
.RI "Create a rectangle instance\&. Makes sure that "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Gets the description from the rectangle "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Draws the rectangle "
.in -1c
.SH "Detailed Description"
.PP 
\fBRectangle\fP \fBIVerb\fP class 

<todo> Correct </todo> 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Rectangle\&.Rectangle (\fBDrawer\fP drawer, \fBIValue\fP width, \fBIValue\fP height)"

.PP
Create a rectangle instance\&. Makes sure that 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIwidth\fP rectangle width
.br
\fIheight\fP rectangle height
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Rectangle\&.ExecuteVerb ()"

.PP
Draws the rectangle 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Rectangle\&.GetDescription ()"

.PP
Gets the description from the rectangle 
.PP
\fBReturns\fP
.RS 4
Describes the rectangle
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
