.TH "Advanced_Software_Engineering.Verbs.Value.ValueContainer" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value.ValueContainer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetVariable\fP (string variableName, \fBIValue\fP iValue)"
.br
.ti -1c
.RI "void \fBDeclareVariable\fP (string variableName, \fBIValue\fP iValue)"
.br
.ti -1c
.RI "void \fBDeclareAndSetVariable\fP (string variableName, \fBIValue\fP iValue)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
