.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Clear" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Clear \- The \fBClear\fP \fBIVerb\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClear\fP (\fBDrawer\fP drawer)"
.br
.RI "Create the clear \fBIVerb\fP "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Execute the clear \fBIVerb\fP\&. It clears the drawer\&. "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes the clearing\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBClear\fP \fBIVerb\fP class\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Clear\&.Clear (\fBDrawer\fP drawer)"

.PP
Create the clear \fBIVerb\fP 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Clear\&.ExecuteVerb ()"

.PP
Execute the clear \fBIVerb\fP\&. It clears the drawer\&. 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Clear\&.GetDescription ()"

.PP
Describes the clearing\&. 
.PP
\fBReturns\fP
.RS 4
A description of clearing
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
