.TH "Advanced_Software_Engineering.Verbs.Value.ValueObjects.PointValue" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value.ValueObjects.PointValue \- A point \fBIValue\fP\&. Simply the same as Point but with IValues intstead of ints\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPointValue\fP (\fBIValue\fP x, \fBIValue\fP y)"
.br
.RI "Create a new \fBPointValue\fP "
.ti -1c
.RI "int \fBGetX\fP ()"
.br
.RI "Get the X component "
.ti -1c
.RI "int \fBGetY\fP ()"
.br
.RI "Get the Y component "
.ti -1c
.RI "Point \fBGetPoint\fP ()"
.br
.RI "Get the Point\&. "
.in -1c
.SH "Detailed Description"
.PP 
A point \fBIValue\fP\&. Simply the same as Point but with IValues intstead of ints\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.Value\&.ValueObjects\&.PointValue\&.PointValue (\fBIValue\fP x, \fBIValue\fP y)"

.PP
Create a new \fBPointValue\fP 
.PP
\fBParameters\fP
.RS 4
\fIx\fP X \fBIValue\fP
.br
\fIy\fP Y \fBIValue\fP
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Point Advanced_Software_Engineering\&.Verbs\&.Value\&.ValueObjects\&.PointValue\&.GetPoint ()"

.PP
Get the Point\&. 
.PP
\fBReturns\fP
.RS 4
Point
.RE
.PP

.SS "int Advanced_Software_Engineering\&.Verbs\&.Value\&.ValueObjects\&.PointValue\&.GetX ()"

.PP
Get the X component 
.PP
\fBReturns\fP
.RS 4
the X component
.RE
.PP

.SS "int Advanced_Software_Engineering\&.Verbs\&.Value\&.ValueObjects\&.PointValue\&.GetY ()"

.PP
Get the Y component 
.PP
\fBReturns\fP
.RS 4
the Y component
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
