.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Quadrilateral" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Quadrilateral \- The \fBQuadrilateral\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuadrilateral\fP (\fBDrawer\fP drawer, \fBPointValue\fP point1, \fBPointValue\fP point2, \fBPointValue\fP point3, \fBPointValue\fP point4)"
.br
.RI "Creates a \fBQuadrilateral\fP instances "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Draws a quadrilateral from the points "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes all of the points "
.in -1c
.SH "Detailed Description"
.PP 
The \fBQuadrilateral\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Quadrilateral\&.Quadrilateral (\fBDrawer\fP drawer, \fBPointValue\fP point1, \fBPointValue\fP point2, \fBPointValue\fP point3, \fBPointValue\fP point4)"

.PP
Creates a \fBQuadrilateral\fP instances 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIpoint1\fP first point
.br
\fIpoint2\fP second point
.br
\fIpoint3\fP third point
.br
\fIpoint4\fP fourth point
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Quadrilateral\&.ExecuteVerb ()"

.PP
Draws a quadrilateral from the points 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Quadrilateral\&.GetDescription ()"

.PP
Describes all of the points 
.PP
\fBReturns\fP
.RS 4
Description of the quadrilateral points
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
