.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Dot" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Dot \- The \fBDot\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDot\fP (\fBDrawer\fP drawer)"
.br
.RI "Creates the \fBDot\fP \fBIVerb\fP "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Draws a dot where the pen currently is\&. "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Gets the description of the command "
.in -1c
.SH "Detailed Description"
.PP 
The \fBDot\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Dot\&.Dot (\fBDrawer\fP drawer)"

.PP
Creates the \fBDot\fP \fBIVerb\fP 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Dot\&.ExecuteVerb ()"

.PP
Draws a dot where the pen currently is\&. 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Dot\&.GetDescription ()"

.PP
Gets the description of the command 
.PP
\fBReturns\fP
.RS 4
The description of the command
.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
