.TH "Advanced_Software_Engineering.Verbs.Value" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeclareVariable\fP"
.br
.RI "Declares a variable "
.ti -1c
.RI "class \fBExpressionValue\fP"
.br
.RI "Expression values are used when there are two IValues that need to be added or subtracted or anything from each other\&. "
.ti -1c
.RI "interface \fBIValue\fP"
.br
.RI "A value "
.ti -1c
.RI "class \fBUpdateVariable\fP"
.br
.RI "Used for updating the variables "
.ti -1c
.RI "class \fBValueContainer\fP"
.br
.ti -1c
.RI "class \fBValueFactory\fP"
.br
.RI "\fBValue\fP factory creates values "
.ti -1c
.RI "class \fBValueHelper\fP"
.br
.RI "This class contains a large amount of useful conversions "
.ti -1c
.RI "class \fBValueStorage\fP"
.br
.RI "The storage for all the values "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
