.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.DrawTo" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.DrawTo \- \fBDrawTo\fP \fBIVerb\fP class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrawTo\fP (\fBDrawer\fP drawer, \fBPointValue\fP point)"
.br
.RI "Creates the \fBDrawTo\fP intstance "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Draws the line "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes how the line is going to be drawn "
.in -1c
.SH "Detailed Description"
.PP 
\fBDrawTo\fP \fBIVerb\fP class 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.DrawTo\&.DrawTo (\fBDrawer\fP drawer, \fBPointValue\fP point)"

.PP
Creates the \fBDrawTo\fP intstance 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIpoint\fP Position to move to
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.DrawTo\&.ExecuteVerb ()"

.PP
Draws the line 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.DrawTo\&.GetDescription ()"

.PP
Describes how the line is going to be drawn 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
