.TH "Advanced_Software_Engineering.Verbs.Value.DeclareVariable" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value.DeclareVariable \- Declares a variable  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeclareVariable\fP (\fBValueStorage\fP storage, string assignment)"
.br
.RI "Creates a new Declare variable "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Sets the variable to null "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Gets the description of the verb "
.ti -1c
.RI "string \fBGetName\fP ()"
.br
.RI "Gets the name of the variable to assign "
.in -1c
.SH "Detailed Description"
.PP 
Declares a variable 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.Value\&.DeclareVariable\&.DeclareVariable (\fBValueStorage\fP storage, string assignment)"

.PP
Creates a new Declare variable 
.PP
\fBParameters\fP
.RS 4
\fIstorage\fP The storage to use
.br
\fIassignment\fP The assignment
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.Value\&.DeclareVariable\&.ExecuteVerb ()"

.PP
Sets the variable to null 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.Value\&.DeclareVariable\&.GetDescription ()"

.PP
Gets the description of the verb 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.Value\&.DeclareVariable\&.GetName ()"

.PP
Gets the name of the variable to assign 
.PP
\fBReturns\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
