.TH "Advanced_Software_Engineering.Verbs.Value.ValueObjects" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.Value.ValueObjects
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColorValue\fP"
.br
.ti -1c
.RI "class \fBPointValue\fP"
.br
.RI "A point \fBIValue\fP\&. Simply the same as Point but with IValues intstead of ints\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
