.TH "Advanced_Software_Engineering.Verbs.DrawingVerbs.Circle" 3 "Sat Dec 12 2020" "Advanced Software Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Advanced_Software_Engineering.Verbs.DrawingVerbs.Circle \- \fBCircle\fP \fBIVerb\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircle\fP (\fBDrawer\fP drawer, \fBIValue\fP scale)"
.br
.RI "\fBCircle\fP constructor creates the \fBCircle\fP \fBIVerb\fP\&. "
.ti -1c
.RI "void \fBExecuteVerb\fP ()"
.br
.RI "Execute the \fBCircle\fP \fBIVerb\fP, which is to draw a circle with the drawer\&. "
.ti -1c
.RI "string \fBGetDescription\fP ()"
.br
.RI "Describes how the circle will be drawn\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCircle\fP \fBIVerb\fP class\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Circle\&.Circle (\fBDrawer\fP drawer, \fBIValue\fP scale)"

.PP
\fBCircle\fP constructor creates the \fBCircle\fP \fBIVerb\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIdrawer\fP drawer
.br
\fIscale\fP scale of the circle
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Circle\&.ExecuteVerb ()"

.PP
Execute the \fBCircle\fP \fBIVerb\fP, which is to draw a circle with the drawer\&. 
.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.
.SS "string Advanced_Software_Engineering\&.Verbs\&.DrawingVerbs\&.Circle\&.GetDescription ()"

.PP
Describes how the circle will be drawn\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBAdvanced_Software_Engineering\&.IVerb\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Advanced Software Engineering from the source code\&.
